### ISSUE TITLE
ImportError: No module named elasticsearch

### ISSUE THREAD

**Issue by kaloyan-s** [ejimz/Elasticsearch-zabbix#13]
Hi, I am using elasticsearch version 2.3.4 and 2.4.0 and Python 2.7.9 and when i run the script i got:

Traceback (most recent call last):
  File "./elastic.py", line 6, in <module>
    from elasticsearch import Elasticsearch
ImportError: No module named elasticsearch

Can you help with this ?

**Comment by jjjbushjjj** [comment]
You need module named elasticsearch. 
You could install it:
pip install elasticsearch

**Comment by fantaziesta** [comment]
I have this trouble as well.

ElasticSearch 2.3.4 and Python 2.7.12 is already installed on the server.
However, I got a message "from elasticsearch import Elasticsearch
ImportError: No module named elasticsearch"
How can I solve it?

**Comment by jjjbushjjj** [comment]
install this http://elasticsearch-py.readthedocs.io/en/master/

**Comment by fantaziesta** [comment]
Thank, I fixed it.

**Comment by kz-ecbatani** [comment]
@jjjbushjjj  and @fantaziesta , I've used pip3 install elasticsearch, it installs it, but when I run python3.7 handler.py, it says module not found. Any ideas why? 

**Installation**

Command: 
`pip3 install elasticsearch
`

```

Collecting elasticsearch
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/ae/43/38329621bcca6f0b97e1cc36fb3cef889414a1960fcdc83a41e26b496634/elasticsearch-7.0.2-py2.py3-none-any.whl
Collecting urllib3>=1.21.1 (from elasticsearch)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Installing collected packages: urllib3, elasticsearch
Successfully installed elasticsearch-7.0.2 urllib3-1.25.3
```


**Output:**
> python3.7 handler.py 
> Traceback (most recent call last):
>   File "handler.py", line 1, in <module>
>     from elasticsearch import Elasticsearch
> ModuleNotFoundError: No module named 'elasticsearch'

**Comment by vishrutarya** [comment]
@koursoh Did you resolve this issue? I appear to have the same problem.

**Comment by junly917** [comment]
try install prefix version 
sudo pip3 install elasticsearch==6.0.0

**Comment by donjpierce** [comment]
@junly917 that solution worked for me (using python3.7 and prefix / Flask on ubuntu16 virtualbox server)

**Comment by kz-ecbatani** [comment]
> @koursoh Did you resolve this issue? I appear to have the same problem.

Sorry for late reply, didn't notice your comment until now.

The following commands should work:

`sudo pip3 install elasticsearch
`or 
`sudo python3 -m pip install elasticsearch`

**Comment by DonaldY** [comment]
@junly917 worked for me (using py3.6 on ubuntu18)
