### ISSUE TITLE
cluster_stats is deprecated

### ISSUE THREAD

**Issue by tduboys** [ejimz/Elasticsearch-zabbix#2]
Hi,

It seems that cluster_stats is deprecated.
Now, ou need to use cluster.node_stats.

I had this error :

```
/etc/zabbix/scripts/ESzabbix.py cluster index_total
Traceback (most recent call last):
  File "/etc/zabbix/scripts/ESzabbix.py", line 40, in <module>
    nodestats = conn.cluster_stats()
AttributeError: 'ES' object has no attribute 'cluster_stats'
```

And I appliyed this patch : 

```
diff --git a/ESzabbix.py b/ESzabbix.py
index 73df8b0..c3081d6 100755
--- a/ESzabbix.py
+++ b/ESzabbix.py
@@ -37,7 +37,7 @@ except Exception, e:

 if sys.argv[1] == 'cluster':
     if sys.argv[2] in clusterkeys:
-        nodestats = conn.cluster_stats()
+        nodestats = conn.cluster.node_stats()
         subtotal = 0
         for nodename in nodestats['nodes']:
             if sys.argv[2] in indexingkeys:
@@ -90,7 +90,7 @@ elif sys.argv[1] == 'service':

 else: # Not clusterwide, check the next arg

-    nodestats = conn.cluster_stats()
+    nodestats = conn.cluster.node_stats()
     print nodestats
     for nodename in nodestats['nodes']:
         if sys.argv[1] in nodestats['nodes'][nodename]['name']:
```

**Comment by volter** [comment]
Confirming the patch to work

**Comment by gcaracuel** [comment]
After this patch I'm getting this new error:

Traceback (most recent call last):
  File "/etc/zabbix/externalscripts/ESzabbix.py", line 47, in <module>
    nodestats = conn.cluster_stats()
AttributeError: 'ES' object has no attribute 'cluster_stats'
[root@es-ves-02 ~]# /etc/zabbix/externalscripts/ESzabbix.py cluster index_total 10.150.113.205 20000
Traceback (most recent call last):
  File "/etc/zabbix/externalscripts/ESzabbix.py", line 47, in <module>
    nodestats = conn.cluster.node_stats()
  File "/usr/lib/python2.7/site-packages/pyes/managers.py", line 630, in node_stats
    return self.conn._send_request('GET', path)
  File "/usr/lib/python2.7/site-packages/pyes/es.py", line 477, in _send_request
    raise_if_error(response.status, decoded)
  File "/usr/lib/python2.7/site-packages/pyes/convert_errors.py", line 85, in raise_if_error
    raise excClass(msg, status, result, request)
pyes.exceptions.IndexMissingException: [_cluster] missing

I'm using pyes 0.99.5

**Comment by tduboys** [comment]
Hi,
It's strange that in your stacktrace, the error is line 47, or the patched line is line 40.

I think the patch dont worked on your case.
But you can patch easily by opening the ESzabbix.py in your favourite text editor, searching for « conn.cluster_stats() » and replace it by « conn.cluster.node_stats() »
There is 2 occurence of cluster_stats() to change.

**Comment by gcaracuel** [comment]
Yes, that's because I need some other previous stuff for my infrastructure but must now affect this.

I tried send a get to:  /_cluster/nodes/stats  and it failed but "/_nodes/stats" is working fine.
So I guess the problem are in pyes 0.99.5 and ES 1.3.2

I started a ticket in the PYES github project.

Thanks for your help!

**Comment by gcaracuel** [comment]
Closed ticket in PYES project. Is known API change in ES 1.3 and 14. Should be fixed in the PYES version.
