### ISSUE TITLE
pyes.exceptions.IndexMissingException: [_cluster] missing

### ISSUE THREAD

**Issue by galindro** [ejimz/Elasticsearch-zabbix#4]
Hi

   I'm getting this error when exec ESzabbix.py:

root@elasticsearch02:/etc/zabbix# /etc/zabbix/zabbix_scripts/ESzabbix.py cluster index_total
Traceback (most recent call last):
  File "/etc/zabbix/zabbix_scripts/ESzabbix.py", line 40, in <module>
    nodestats = conn.cluster.node_stats()
  File "/usr/local/lib/python2.7/dist-packages/pyes/managers.py", line 620, in node_stats
    return self.conn._send_request('GET', path)
  File "/usr/local/lib/python2.7/dist-packages/pyes/es.py", line 470, in _send_request
    raise_if_error(response.status, decoded)
  File "/usr/local/lib/python2.7/dist-packages/pyes/convert_errors.py", line 85, in raise_if_error
    raise excClass(msg, status, result, request)
pyes.exceptions.IndexMissingException: [_cluster] missing

This is my pyes version:

root@elasticsearch02:~# pip freeze |grep pyes
pyes==0.99.0

**Comment by galindro** [comment]
This is my ES version:

root@elasticsearch02:~# dpkg --list elasticsearch
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                Version                             Description
+++-===================================-===================================-======================================================================================
ii  elasticsearch                       1.1.0                               Open Source, Distributed, RESTful Search Engine

   Is pyes compatible with ES version 1.1.0? I could not find any version correlation between them

**Comment by gcaracuel** [comment]
API changed in ES 1.3 and 1.4 now node_stats must be quried using: "/_nodes/stats" instead of "_cluster" index.

Is a known issue in PYES. See: https://github.com/aparo/pyes/issues/462

Should be fixed shortly.

**Comment by bauerstefan** [comment]
Here is a patch that did work at least for me:

--- managers.py.orig    2015-02-11 14:20:49.428124337 +0100
+++ managers.py 2015-02-11 14:53:30.283293505 +0100
@@ -495,11 +495,11 @@
         if all_nodes:
             path = make_path('_shutdown')
         elif master:
-            path = make_path("_cluster", "nodes", "_master", "_shutdown")
+            path = make_path("_nodes", "_master", "_shutdown")
         elif nodes:
-            path = make_path("_cluster", "nodes", ",".join(nodes), "_shutdown")
+            path = make_path("_nodes", ",".join(nodes), "_shutdown")
         elif local:
-            path = make_path("_cluster", "nodes", "_local", "_shutdown")
+            path = make_path("_nodes", "_local", "_shutdown")
         if delay:
             try:
                 int(delay)
@@ -574,7 +574,7 @@
                                list of indices to include in the response.

         """
-        path = make_path("_cluster", "state")
+        path = make_path("_", "state")
         parameters = {}

         if filter_nodes is not None:
@@ -602,7 +602,7 @@
         The cluster :ref:`nodes info <es-guide-reference-api-admin-cluster-state>` API allows to retrieve one or more (or all) of
         the cluster nodes information.
         """
-        parts = ["_cluster", "nodes"]
+        parts = ["_nodes"]
         if nodes:
             parts.append(",".join(nodes))
         path = make_path(*parts)
@@ -622,9 +622,9 @@
         The cluster :ref:`nodes info <es-guide-reference-api-admin-cluster-nodes-stats>` API allows to retrieve one or more (or all) of
         the cluster nodes information.
         """
-        parts = ["_cluster", "nodes", "stats"]
+        parts = ["_nodes", "stats"]
         if nodes:
-            parts = ["_cluster", "nodes", ",".join(nodes), "stats"]
+            parts = ["_nodes", ",".join(nodes), "stats"]

         path = make_path(*parts)
         return self.conn._send_request('GET', path)

**Comment by bauerstefan** [comment]
Here is a patch that did work at least for me:

http://pastebin.com/4Ef1W4Jc

**Comment by ejimz** [comment]
Please add the code as a patch to merge
