### ISSUE TITLE
monitor elasticsearch with zabbix

### ISSUE THREAD

**Issue by learnhub17** [ejimz/Elasticsearch-zabbix#6]
Dear Sir,
post on github (https://github.com/serialsito/Elasticsearch-zabbix) regarding elasticsearch-zabbix, i tried a lot to get successfully monitor ES but failed, i thing m doing something wrong : i want to know where we have to put .py and .userparm file , is this will be configure over zabbix server or over ES-client which i want to monitor ?

by configuring .py and .userparm over zabbix-server i got this error : 
item [test:ESzabbix[cluster,status]] became not supported: ZBX_NOTSUPPORTED
1299:20150409:110848.606 item [test:ESzabbix[cluster,unassigned_shards]] became not supported: ZBX_NOTSUPPORTED
1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},field_size_in_bytes]] became not supported: ZBX_NOTSUPPORTED
1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},filter_size_in_bytes]] became not supported: ZBX_NOTSUPPORTED
1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},index_total]] became not supported: ZBX_NOTSUPPORTED
1299:20150409:110848.607 item [test:ESzabbix[{$NODENAME},size_in_bytes]] became not supported: ZBX_NOTSUPPORTED
1299:20150409:110848.608 item [test:ESzabbix[service,status]] became not supported: ZBX_NOTSUPPORTED

**Comment by czhujer** [comment]
Hi,
this temlate script ESzabbix.py/template probably is not maintained, as you can see in other issues.
Same problem is with pyes library (ESzabbix.py is using pyes)

I have to fix pyes files (few week ago i solve similar things).
Try replate this files.. https://github.com/H-Software/puppet-zabbixagent/tree/master/files/pyes-fixedfiles
Or you can use add puppet manifest :) https://github.com/H-Software/puppet-zabbixagent

But now i found out this pull request ...i have to try :+1: 
https://github.com/serialsito/Elasticsearch-zabbix/pull/5

**Comment by ejimz** [comment]
The PR is accepted, so now it should be works
