### ISSUE TITLE
Error importing template, zabbix 2.4

### ISSUE THREAD

**Issue by Jefl** [ejimz/Elasticsearch-zabbix#9]
Hi,

I got the following error while importing the template:

> Cannot find value map "ES Cluster State" used for item "ElasticSearch Cluster Status" on "Elasticsearch Cluster".

I removed the reference to the valuemap from the template:

```
<valuemap>
                     <name>ES Cluster State</name>
</valuemap>
```

And was able to import it properly.

I would like to fix the issue though, would you tell me what is wrong exactely ?

**Comment by alpheus55** [comment]
@Jefl you should add "ES Cluster State" to the valuemap first(0 ⇒ Green,1 ⇒ Yellow,2 ⇒ Red), then import the template. the error happens because of it's can't find the valuemap. hope it's helps.

**Comment by Jefl** [comment]
@alpheus55 thank you, I figures out that something was missing but I was not able to find where.
For the record value mapping are located in Administration -> General -> value mapping from the dropdown list.

I have an other issue but will fill up a new issue.
